## Sevice Container ########################
version: '2'
services:
  server:
    build: .
    command: npm run dev
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "5000:5000"
    depends_on:
      - mongodb

  mongodb:
    image: mongo
    environment:
      - MONGODB_DATABASE=beers-db
    ports:
      - "27017:27017"

  mongo-seed:
    build: ./mongo-seed
    links:
      - mongodb

### Add more Containers below ###############################
networks:
    default:
        external:
            name: microservicenetwork